# TravisCI
#
# @url: https://github.com/caskroom/homebrew-cask/blob/master/.travis.yml
# @url: http://docs.travis-ci.com/user/languages/objective-c/
#
language: ruby

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      rvm: system
  fast_finish: true

before_install:
  - brew update || brew update
  - brew install python3 ruby

script:
  - brew install kazuakim/macvim/macvim-kaoriya

after_success:
  - printenv PATH
  - /usr/bin/which ctags   && ctags   --version
  - /usr/bin/which lua     && lua     -v
  - /usr/bin/which luajit  && luajit  -v
  - /usr/bin/which perl    && perl    -v
  - /usr/bin/which python3 && python3 --version
  - /usr/bin/which ruby    && ruby    --version
  - /usr/local/opt/macvim-kaoriya/MacVim.app/Contents/MacOS/vim --version

notifications:
  email: false

# vim:fdl=0:sts=2:sw=2:ts=2
