# TravisCI
#
# @url: https://github.com/caskroom/homebrew-cask/blob/master/.travis.yml
# @url: http://docs.travis-ci.com/user/languages/objective-c/
#
language: ruby

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      rvm: system
  fast_finish: true

before_install:
  - brew update || brew update
  - brew upgrade python3

script:
  - brew install --HEAD ./macvim-kaoriya.rb

after_success:
  - brew test macvim-kaoriya

notifications:
  email: false

# vim:fdl=0:sts=2:sw=2:ts=2
