# TravisCI
#
# @url: https://github.com/caskroom/homebrew-cask/blob/master/.travis.yml
# @url: http://docs.travis-ci.com/user/languages/objective-c/
#
language: objective-c
os:
  - osx

osx_image:     xcode8.2
xcode_project: MacVim.xcodeproj
xcode_scheme:  MacVim
sudo:          false

# before_install steps
# * update Homebrew
# * set PATH according to env matrix
before_install:
  - brew update || brew update
  - brew install python3 ruby xctool

# install steps
# * brew Formulae, install and version view
install:
  - brew install --HEAD kazuakim/macvim/macvim-kaoriya
  - printenv PATH
  - /usr/bin/which ctags   && ctags   --version
  - /usr/bin/which lua     && lua     -v
  - /usr/bin/which luajit  && luajit  -v
  - /usr/bin/which perl    && perl    -v
  - /usr/bin/which python3 && python3 --version
  - /usr/bin/which ruby    && ruby    --version
  - /usr/local/opt/macvim-kaoriya/MacVim.app/Contents/MacOS/vim --version

notifications:
  email: false

# vim:fdl=0:sts=2:sw=2:ts=2
